$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  build_transcriptome:
    type: object
    properties:
      fa:
        type: string
      gtf:
        type: string
    required:
      - fa
      - gtf
  
  integration:
    type: object
    properties:
      species1:
        enum:
          - mouse
          - human
          - marmoset
          - mallard_duck
          - common_carp
          - guinea_pig
      species2:
        enum:
          - mouse
          - human
          - marmoset
          - mallard_duck
          - common_carp
          - guinea_pig
    required:
      - species1
      - species2

  evaluate_reads:
    type: boolean
  
  previous_run:
    type: object
    properties:
      run_id: 
        type: string
    required:
      - run_id
  
  new_run: 
    type: object
    properties:
      run_id:
        type: string
      is_new_run:
        type: boolean
    required:
      - is_new_run

  species:
    enum:
      - mouse
      - human
      - marmoset
      - mallard_duck
      - common_carp
      - guinea_pig

  raw_reads:
    type: object
    properties:
      fastq:
        type: string
    required:
      - fastq

required:
  - species
  - raw_reads
