build_transcriptome: false
comments: ''
do_alignment: true
fasta_file: ''
gtf_file: ''
raw_reads: /data/public-data/scpipeline_data/raw_reads
run_id: 3c916259a29011ba77206afd49d99187
run_status: Queued
species: Demo_ducks1
