# Make sure that the input species name is the same as the name of the transcriptome for the 
# particluar genome. 

species: common_marmoset

raw_reads:
  fastq: "raw_reads/"

# build_transcriptome:
#   fa: "genome_files/common_marmoset/Callithrix_jacchus.mCalJac1.pat.X.dna.primary_assembly.fa"
#   gtf: "genome_files/common_marmoset/Callithrix_jacchus.mCalJac1.pat.X.105.filtered.gtf"

# previous_run: 
#   run_id: "12235asdlkjvk8sjls"