# Default config.yaml file. Allows the user to choose between either the 
# alignment or the analysis pipeline. 

# Variables related to the alignment of raw reads. 
# do_alignment: true
# run_id: 'random'
# species: 'mouse'
# build_transcriptome: false
# fasta_file: ""
# gtf_file: ""
# raw_reads: "reads_location/"

# # Variables related to the analysis of gene count matrix. 
do_analysis: true
anal_id:  'something'
species_1: 'mouse'
gene_mtx_1: 'mouse_gene_mtx.h5' 
integration: false
species_2: 'marmoset'
gene_mtx_2: 'marmoset_gene_mtx.h5'
