
$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object


properties:

  # Variables related to the alignment of raw reads. 
  
  do_alignment:
    type: boolean

  run_id: 
    type: string 

  species: 
    type: string 

  build_transcriptome: 
    type: boolean 

  fasta_file: 
    type: string 

  gtf_file: 
    type: string 

  raw_reads: 
    type: string 

  # Variables related to the analysis of gene count matrix. 

  do_analysis:
    type: boolean

  anal_id: 
    type: string 

  species_1: 
    type: string 

  gene_mtx_1: 
    type: string 

  integration: 
    type: boolean 

  species_2: 
    type: string 

  gene_mtx_2: 
    type: string 

dependentRequired:
  do_alignment:
    - run_id
    - species  
    - raw_reads

  do_analysis:
    - anal_id
    - species_1
    - gene_mtx_1
    - integration

if: 
  properties:
    integration: true
    required: 
      - integration
then:
  required:
    - fasta_file
    - gtf_file